<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aSA" nsURI="http://www.example.org/aSA" nsPrefix="aSA">
  <eSubpackages name="M2" nsURI="http://www.example.org/aSA/M2" nsPrefix="M2">
    <eClassifiers xsi:type="ecore:EClass" name="ArchitecturalElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
          eType="#//M2/Interface" containment="true" eOpposite="#//M2/Interface/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//M2/ArchitecturalElement" containment="true" eOpposite="#//M2/ArchitecturalElement/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//M2/ArchitecturalElement"
          eOpposite="#//M2/ArchitecturalElement/elements"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//M2/ArchitecturalElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subConfiguration" eType="#//M2/Configuration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
          eType="#//M2/Binding"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attachment" upperBound="-1"
          eType="#//M2/Attachment"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentInterfaces"
          lowerBound="2" upperBound="-1" eType="#//M2/ComponentInterface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//M2/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#//M2/Constraint" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Configuration" eSuperTypes="#//M2/ArchitecturalElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" lowerBound="1"
          upperBound="-1" eType="#//M2/Component"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
          eType="#//M2/Connector"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="configurationPorts" lowerBound="1"
          upperBound="-1" eType="#//M2/Port"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Connector" abstract="true" eSuperTypes="#//M2/ArchitecturalElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="glue" lowerBound="1"
          upperBound="-1" eType="#//M2/Glue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UserConnector" eSuperTypes="#//M2/Connector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subConfiguration" eType="#//M2/Configuration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attachment" upperBound="-1"
          eType="#//M2/Attachment"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectorInterfaces"
          lowerBound="2" upperBound="-1" eType="#//M2/ConnectorInterface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BuiltInConnector" abstract="true"
        eSuperTypes="#//M2/Connector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//M2/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//M2/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Glue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//M2/ArchitecturalElement" eOpposite="#//M2/ArchitecturalElement/interfaces"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Binding" eSuperTypes="#//M2/BuiltInConnector"/>
    <eClassifiers xsi:type="ecore:EClass" name="Attachment" eSuperTypes="#//M2/BuiltInConnector"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentInterface" abstract="true"
        eSuperTypes="#//M2/Interface">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
          eType="#//M2/Binding"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConnectorInterface" abstract="true"
        eSuperTypes="#//M2/Interface">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//M2/ComponentInterface"/>
    <eClassifiers xsi:type="ecore:EClass" name="Service" abstract="true" eSuperTypes="#//M2/ComponentInterface"/>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredPort" eSuperTypes="#//M2/Port"/>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredService" eSuperTypes="#//M2/Service"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedPort" eSuperTypes="#//M2/Port"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedService" eSuperTypes="#//M2/Service"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConnectorService" eSuperTypes="#//M2/ConnectorInterface"/>
    <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true" eSuperTypes="#//M2/ConnectorInterface"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedRole" eSuperTypes="#//M2/Role"/>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredRole" eSuperTypes="#//M2/Role"/>
    <eClassifiers xsi:type="ecore:EClass" name="Property"/>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint"/>
  </eSubpackages>
</ecore:EPackage>
